# Script to autorenew dns records with Let's Encrypt
# Not Functional Yet

CERTBOT="/home/alex/automated/certbot-auto"

# These will be loaded from file.
EMAIL="REDACTED"
API_KEY="REDACTED"

# Provided By Cloudflare Website
# Can also be retrieved by submitting a GET api request to https://api.cloudflare.com/client/v4/zones/.
ZONE_ID="Provided By Cloudflare Website"

# Allows For Lookup Of Existing Records In DNS Zone
RECORDS=$(curl -X GET "https://api.cloudflare.com/client/v4/zones/"$ZONE_ID"/dns_records/" \
     -H "X-Auth-Email: "$EMAIL \
     -H "X-Auth-Key: "$API_KEY \
     -H "Content-Type: application/json")

TXT_RECORD="_acme-challenge" # _acme-challenge.web - Should be provided as an argument
Record_ID="Provided By Cloudflare API"

# sudo /home/alex/automated/certbot-auto certonly --manual -d '*.senorcontento.com'
# sudo /home/alex/automated/certbot-auto certonly --manual -d '*.web.senorcontento.com'

PROOF="Generated By Certbot Auto..."

curl -X PUT "https://api.cloudflare.com/client/v4/zones/"$ZONE_ID"/dns_records/"$Record_ID \
     -H "X-Auth-Email: "$EMAIL \
     -H "X-Auth-Key: "$API_KEY \
     -H "Content-Type: application/json" \
     --data '{"type":"TXT","name":"'$TXT_RECORD'","content":"'$PROOF'","ttl":1,"proxied":false}'